Repository SOPT-all/35-COLLABORATION-WEB-AGODA, pull requests merged in 2024-11, with the labels that each got.

#6 [Chore] 스타일 초기화, 글로벌 스타일, theme, router 설정
  index.html
  package.json
  src/App.tsx
  src/pages/CityPage/CityPage.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/HotelDetailPage/HotelDetailPage.tsx
  src/pages/HotelListPage/HotelListPage.tsx
  src/routes/.gitkeep
  src/routes/pageRoutes.tsx
  src/routes/routePath.ts
  src/styles/.gitkeep
  src/styles/emtion.d.ts
  src/styles/global.ts
  src/styles/reset.ts
  src/styles/theme.ts
  src/types/.gitkeep
  src/types/routeType.ts
  tsconfig.app.json
  vite.config.ts
  yarn.lock
Labels: ⚙️ Setting, 🪼 채연

#10 [ Feat] 별점(등급) 컴포넌트 추가
  package.json
  public/svg/.gitkeep
  public/svg/ic_star.svg
  public/svg/ic_star_blue.svg
  src/assets/.gitkeep
  src/assets/custom.d.ts
  src/assets/svg/IcStar.tsx
  src/assets/svg/IcStarBlue.tsx
  src/assets/svg/index.ts
  src/components/StarRating/StarRating.style.ts
  src/components/StarRating/StarRating.tsx
  tsconfig.app.json
  vite.config.ts
  yarn.lock
Labels: ✨ Feature, ⚙️ Setting, 🦭 민하

#14 [Feat] 버튼 컴포넌트 추가
  src/components/Button/Button.style.ts
  src/components/Button/Button.tsx
Labels: ✨ Feature, 🐬 수정

#12 [Feat] 헤더 컴포넌트 추가
  public/svg/ic_back.svg
  public/svg/ic_cart.svg
  public/svg/ic_logo.svg
  public/svg/ic_menu.svg
  src/assets/svg/IcBack.tsx
  src/assets/svg/IcCart.tsx
  src/assets/svg/IcLogo.tsx
  src/assets/svg/IcMenu.tsx
  src/assets/svg/index.ts
  src/components/.gitkeep
  src/components/Header/Header.style.ts
  src/components/Header/Header.tsx
  src/pages/HomePage/HomePage.tsx
  src/styles/theme.ts
  yarn.lock
Labels: ✨ Feature, 🪼 채연

#20 [Feat] 호텔 리스트 페이지 추가
  public/svg/ic_check_coupon.svg
  public/svg/ic_empty_heart.svg
  public/svg/ic_fill_heart.svg
  public/svg/ic_filter.svg
  public/svg/ic_map.svg
  public/svg/ic_search.svg
  public/svg/tag_lightred.svg
  src/assets/svg/IcCheckCoupon.tsx
  src/assets/svg/IcEmptyHeart.tsx
  src/assets/svg/IcFillHeart.tsx
  src/assets/svg/IcFilter.tsx
  src/assets/svg/IcMap.tsx
  src/assets/svg/IcSearch.tsx
  src/assets/svg/TagLightred.tsx
  src/assets/svg/index.ts
  src/pages/HotelListPage/HotelListPage.style.ts
  src/pages/HotelListPage/HotelListPage.tsx
  src/pages/HotelListPage/components/HotelListCard/HotelListCard.style.ts
  src/pages/HotelListPage/components/HotelListCard/HotelListCard.tsx
  src/pages/HotelListPage/components/HotelListFooter.style.ts
  src/pages/HotelListPage/components/HotelListFooter.tsx
  src/pages/HotelListPage/components/OptionBar.style.ts
  src/pages/HotelListPage/components/OptionBar.tsx
  src/pages/HotelListPage/components/SaleBox.style.ts
  src/pages/HotelListPage/components/SaleBox.tsx
  src/pages/HotelListPage/components/SearchBar.style.ts
  src/pages/HotelListPage/components/SearchBar.tsx
  src/styles/iconStyles.ts
  src/types/hotelList.ts
  src/utils/mocks/.gitkeep
  src/utils/mocks/hotelListData.ts
  yarn.lock
Labels: ✨ Feature, 🦭 민하

#22 [Feat] 도시 페이지 추가
  public/svg/ic_back_white.svg
  public/svg/ic_cancle.svg
  src/assets/svg/IcBackWhite.tsx
  src/assets/svg/IcCancle.tsx
  src/assets/svg/index.ts
  src/pages/CityPage/CityPage.style.ts
  src/pages/CityPage/CityPage.tsx
  src/pages/CityPage/components/CityCard/CityCard.style.ts
  src/pages/CityPage/components/CityCard/CityCard.tsx
  src/pages/CityPage/components/CityHeader/CityHeader.style.ts
  src/pages/CityPage/components/CityHeader/CityHeader.tsx
  src/pages/HotelListPage/HotelListPage.tsx
  src/utils/mocks/cities.ts
Labels: ✨ Feature, 🪼 채연

#23 [Feat] 홈 페이지 추가
  public/svg/ic_activity.svg
  public/svg/ic_bus.svg
  public/svg/ic_car.svg
  public/svg/ic_car_bus.svg
  public/svg/ic_checkin.svg
  public/svg/ic_checkout.svg
  public/svg/ic_flights.svg
  public/svg/ic_packages.svg
  public/svg/ic_person.svg
  public/svg/ic_separator.svg
  public/svg/ic_sim.svg
  public/svg/ic_stay.svg
  public/svg/ic_vipchip.svg
  src/assets/img/home_background.png
  src/assets/svg/IcActivity.tsx
  src/assets/svg/IcBus.tsx
  src/assets/svg/IcCar.tsx
  src/assets/svg/IcCarBus.tsx
  src/assets/svg/IcCheckin.tsx
  src/assets/svg/IcCheckout.tsx
  src/assets/svg/IcFlights.tsx
  src/assets/svg/IcPackages.tsx
  src/assets/svg/IcPerson.tsx
  src/assets/svg/IcSearch.tsx
  src/assets/svg/IcSeparator.tsx
  src/assets/svg/IcSim.tsx
  src/assets/svg/IcStay.tsx
  src/assets/svg/IcVipchip.tsx
  src/assets/svg/index.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/components/BarTravel/BarTravel.style.ts
  src/pages/HomePage/components/BarTravel/BarTravel.tsx
  src/pages/HomePage/components/CategoryButton/CategoryButton.style.ts
  src/pages/HomePage/components/CategoryButton/CategoryButton.tsx
  src/pages/HomePage/components/HomeCard/HomeCard.style.ts
  src/pages/HomePage/components/HomeCard/HomeCard.tsx
  src/pages/HomePage/components/HomeChip/HomeChip.style.ts
  src/pages/HomePage/components/HomeChip/HomeChip.tsx
  src/pages/HomePage/components/HomeHeader/HomeHeader.tsx
  src/pages/HomePage/components/HomeHeader/HomeHeder.style.ts
  src/pages/HomePage/components/ListWithButton/ListWithButton.style.ts
  src/pages/HomePage/components/ListWithButton/ListWithButton.tsx
  src/pages/HomePage/components/Spacing.tsx
  src/pages/HotelListPage/components/SearchBar.style.ts
  src/utils/constants/.gitkeep
  src/utils/constants/home/categoryConstants.ts
  src/utils/constants/home/chipConstants.ts
  src/utils/mocks/homeData.ts
Labels: ✨ Feature, 🐬 수정

#34 [Setting]: Tanstack Query, API 초기 세팅
  package.json
  src/App.tsx
  src/apis/instance.ts
  src/utils/constants/api/api.ts
  yarn.lock
Labels: ⚙️ Setting, 🦭 민하

#25 [Feat] 호텔 리스트 페이지 시간한정세일 기능 추가
  public/svg/ic_clock.svg
  src/assets/svg/IcClock.tsx
  src/assets/svg/index.ts
  src/pages/HotelListPage/HotelListPage.tsx
  src/pages/HotelListPage/components/HotelListCard/HotelListCard.tsx
  src/pages/HotelListPage/components/OptionBar.style.ts
  src/pages/HotelListPage/components/OptionBar.tsx
  src/pages/HotelListPage/components/SearchBar.style.ts
  src/pages/HotelListPage/components/TimeSaleCard/TimeSaleCard.style.ts
  src/pages/HotelListPage/components/TimeSaleCard/TimeSaleCard.tsx
  src/pages/HotelListPage/components/TimeSaleSection.style.ts
  src/pages/HotelListPage/components/TimeSaleSection.tsx
  src/pages/HotelListPage/components/TimeSaleTitle.style.ts
  src/pages/HotelListPage/components/TimeSaleTitle.tsx
  src/utils/mocks/hotelListData.ts
  src/utils/scrollUtils.ts
Labels: ✨ Feature, 🦭 민하

#27 [Feat] 호텔 상세 페이지 내 객실 정보 컴포넌트
  public/svg/ic_bath.svg
  public/svg/ic_bed.svg
  public/svg/ic_cart_2.svg
  public/svg/ic_ticket_green.svg
  public/svg/ic_ticket_red.svg
  src/assets/svg/IcBath.tsx
  src/assets/svg/IcBed.tsx
  src/assets/svg/IcCart2.tsx
  src/assets/svg/IcTicketGreen.tsx
  src/assets/svg/IcTicketRed.tsx
  src/assets/svg/index.ts
  src/pages/HotelDetailPage/Components/HotelDetail/Location.style.ts
  src/pages/HotelDetailPage/HotelDetailPage.style.ts
  src/pages/HotelDetailPage/HotelDetailPage.tsx
  src/pages/HotelDetailPage/components/RoomDetail/RoomDetail.style.ts
  src/pages/HotelDetailPage/components/RoomDetail/RoomDetail.tsx
  src/pages/HotelDetailPage/components/RoomDetailCard/RoomDetailCard.style.ts
  src/pages/HotelDetailPage/components/RoomDetailCard/RoomDetailCard.tsx
  src/pages/HotelDetailPage/components/RoomDetailChip/RoomDetailChip.style.ts
  src/pages/HotelDetailPage/components/RoomDetailChip/RoomDetailChip.tsx
  src/pages/HotelDetailPage/components/RoomDetailPriceCard/RoomDetailPriceCard.style.ts
  src/pages/HotelDetailPage/components/RoomDetailPriceCard/RoomDetailPriceCard.tsx
  src/types/hotelDetail.ts
  src/utils/constants/roomDetailChipData.ts
  src/utils/constants/roomDetailPriceData.ts
  src/utils/mocks/roomData.ts
Labels: ✨ Feature, 🪼 채연

#42 [Feat] 호텔리스트 페이지 API 연결
  src/apis/hotel/useFetchHotelList.ts
  src/pages/HotelListPage/HotelListPage.tsx
  src/pages/HotelListPage/components/SearchBar.tsx
  src/pages/HotelListPage/components/TimeSaleSection.tsx
  src/routes/routePath.ts
  src/types/apiResponseType.ts
  src/types/hotelList.ts
  src/utils/constants/api/queryKey.ts
  tsconfig.app.json
Labels: ✨ Feature, 🦭 민하

#55 [Feat] Error 핸들링
  package.json
  src/App.tsx
  src/apis/error.ts
  src/apis/hotel/useFetchHotelList.ts
  src/apis/instance.ts
  src/assets/img/img_error.png
  src/components/Error/ErrorFallback.style.ts
  src/components/Error/ErrorFallback.tsx
  src/components/Error/NotFound.tsx
  src/routes/Layout.tsx
  src/routes/pageRoutes.tsx
  src/utils/constants/api/errorMessage.ts
  yarn.lock
Labels: ✨ Feature, 🦭 민하

#45 [Feat] home - city - hotelList 페이지 네비게이션
  src/pages/CityPage/components/CityCard/CityCard.tsx
  src/pages/HomePage/components/BarTravel/BarTravel.tsx
  src/pages/HotelListPage/components/SearchBar.tsx
Labels: ✨ Feature, 🪼 채연

#53 [Feat] 호텔 상세 페이지 하단 영역 구현
  public/svg/ic_city_search.svg
  public/svg/ic_people_black.svg
  public/svg/ic_room_black.svg
  src/assets/svg/IcCitySearch.tsx
  src/assets/svg/IcPeopleBlack.tsx
  src/assets/svg/IcRoomBlack.tsx
  src/assets/svg/index.ts
  src/pages/CityPage/components/CityHeader/CityHeader.tsx
  src/pages/HotelDetailPage/Components/RoomDescription/RoomDescription.style.ts
  src/pages/HotelDetailPage/Components/RoomDescription/RoomDescription.tsx
  src/pages/HotelDetailPage/Components/RoomDescriptionCard/RoomDescriptionCard.style.ts
  src/pages/HotelDetailPage/Components/RoomDescriptionCard/RoomDescriptionCard.tsx
  src/pages/HotelDetailPage/HotelDetailPage.style.ts
  src/pages/HotelDetailPage/HotelDetailPage.tsx
  src/pages/HotelDetailPage/components/RoomDetail/RoomDetail.style.ts
  src/pages/HotelDetailPage/components/RoomDetail/RoomDetail.tsx
  src/pages/HotelDetailPage/components/RoomDetailCard/RoomDetailCard.tsx
  src/pages/HotelDetailPage/components/RoomDetailPriceCard/RoomDetailPriceCard.tsx
  src/pages/HotelListPage/components/HotelListCard/HotelListCard.tsx
  src/utils/constants/hotelDetail/hotelInfoData.ts
  src/utils/constants/hotelDetail/roomDetailChipData.ts
  src/utils/constants/hotelDetail/roomDetailPriceData.ts
Labels: ✨ Feature, 🪼 채연

#51 [Feat] HotelDetail 페이지 Room API 연결
  package.json
  public/svg/ic_city_search.svg
  public/svg/ic_people_black.svg
  public/svg/ic_room_black.svg
  src/App.tsx
  src/apis/error.ts
  src/apis/hotel/useFetchHotelList.ts
  src/apis/hoteldetail/useFetchRoomDetail.ts
  src/apis/instance.ts
  src/assets/img/img_error.png
  src/assets/svg/IcCitySearch.tsx
  src/assets/svg/IcPeopleBlack.tsx
  src/assets/svg/IcRoomBlack.tsx
  src/assets/svg/index.ts
  src/components/Error/ErrorFallback.style.ts
  src/components/Error/ErrorFallback.tsx
  src/components/Error/NotFound.tsx
  src/pages/CityPage/components/CityCard/CityCard.tsx
  src/pages/CityPage/components/CityHeader/CityHeader.tsx
  src/pages/HomePage/components/BarTravel/BarTravel.tsx
  src/pages/HotelDetailPage/Components/RoomDescription/RoomDescription.style.ts
  src/pages/HotelDetailPage/Components/RoomDescription/RoomDescription.tsx
  src/pages/HotelDetailPage/Components/RoomDescriptionCard/RoomDescriptionCard.style.ts
  src/pages/HotelDetailPage/Components/RoomDescriptionCard/RoomDescriptionCard.tsx
  src/pages/HotelDetailPage/HotelDetailPage.style.ts
  src/pages/HotelDetailPage/HotelDetailPage.tsx
  src/pages/HotelDetailPage/components/RoomDetail/RoomDetail.style.ts
  src/pages/HotelDetailPage/components/RoomDetail/RoomDetail.tsx
  src/pages/HotelDetailPage/components/RoomDetailCard/RoomDetailCard.tsx
  src/pages/HotelDetailPage/components/RoomDetailPriceCard/RoomDetailPriceCard.tsx
  src/pages/HotelListPage/components/HotelListCard/HotelListCard.tsx
  src/pages/HotelListPage/components/SearchBar.tsx
  src/routes/Layout.tsx
  src/routes/pageRoutes.tsx
  src/types/hotelDetail.ts
  src/utils/constants/api/errorMessage.ts
  src/utils/constants/api/queryKey.ts
  src/utils/constants/hotelDetail/hotelInfoData.ts
  src/utils/constants/hotelDetail/roomDetailChipData.ts
  src/utils/constants/hotelDetail/roomDetailPriceData.ts
  yarn.lock
Labels: ✨ Feature, 🐬 수정

#48 [Feat] City - 도시 리스트 api 연결
  src/apis/city/useFetchCities.ts
  src/pages/CityPage/CityPage.tsx
  src/types/city.ts
  src/utils/constants/api/queryKey.ts
Labels: ✨ Feature, 🪼 채연

#54 [Feat] 좋아요 버튼 구현/ API 연결
  public/svg/emptyheart.svg
  public/svg/fillheart.svg
  src/apis/hoteldetail/useFetchHotelDetail.ts
  src/assets/svg/Emptyheart.tsx
  src/assets/svg/Fillheart.tsx
  src/assets/svg/index.ts
  src/pages/HotelDetailPage/Components/HotelDetail/HeartBtn.style.ts
  src/pages/HotelDetailPage/Components/HotelDetail/HeartBtn.tsx
  src/pages/HotelDetailPage/Components/HotelDetail/Like/IsLiked.style.ts
  src/pages/HotelDetailPage/Components/HotelDetail/Like/IsLiked.tsx
  src/pages/HotelDetailPage/HotelDetailPage.style.ts
  src/pages/HotelDetailPage/HotelDetailPage.tsx
Labels: ✨ Feature, 🐡 윤지

#52 Update README.md
  README.md
Labels: 🐬 수정
